name: .NET Core

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_SECRET_KEY}}
    - name: Install dependencies
      run: dotnet restore
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/*/ | cut -d "v" -f 2}
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack eFormApi.BasePn.sln -c Release -o ./artifacts -p:PackageVersion=${{ steps.get_version.outputs.VERSION }}
    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./artifacts/Microting.eFormApi.BasePn.${{ steps.get_version.outputs.VERSION }}.nupkg" --skip-duplicate --no-symbols true
